apiVersion: v1
kind: ConfigMap
metadata:
  name: hello-grpc-config
  namespace: basic-kube
  labels:
    app.kubernetes.io/name: hello-grpc
    app.kubernetes.io/part-of: basic-kube
data:
  DJANGO_DEBUG: "True"
  DJANGO_ALLOWED_HOSTS: "localhost,127.0.0.1,*"
