apiVersion: v1
kind: Secret
metadata:
  name: hello-grpc-secret
  namespace: basic-kube
  labels:
    app.kubernetes.io/name: hello-grpc
    app.kubernetes.io/part-of: basic-kube
type: Opaque
stringData:
  DJANGO_SECRET_KEY: "django-insecure-replace-me-with-a-real-secret-in-prod"
